name: Deploy Worker
on:
  push:
    paths:
      - 'worker/**'
      - 'common/**'
      - '.github/workflows/deploy-worker.yml'
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}
    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/bugdash-worker ./worker
    - run: |
        CONN=$(gcloud sql instances describe bugdash-sql --format='value(connectionName)')
        gcloud run deploy bugdash-worker --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/bugdash-worker \
          --region ${{ secrets.GCP_REGION }} --no-allow-unauthenticated \
          --add-cloudsql-instances $CONN \
          --set-env-vars CLOUDSQL_INSTANCE=$CONN,DB_NAME=bugdash,DB_USER=postgres,DB_PASS=${{ secrets.DB_PASS }} \
          --set-env-vars GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }},REGION=${{ secrets.GCP_REGION }} \
          --set-env-vars SUBSCRIPTION=bugdash-worker-pull,GCS_BUCKET=bugdash-artifacts-${{ secrets.GCP_PROJECT_ID }},WORKER_CONCURRENCY=4 \
          --cpu 2 --memory 2Gi --max-instances 10
