name: Deploy API
on:
  push:
    paths:
      - 'api/**'
      - 'common/**'
      - '.github/workflows/deploy-api.yml'
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}
    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/bugdash-api ./api
    - run: |
        CONN=$(gcloud sql instances describe bugdash-sql --format='value(connectionName)')
        gcloud run deploy bugdash-api --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/bugdash-api \
          --region ${{ secrets.GCP_REGION }} --allow-unauthenticated \
          --add-cloudsql-instances $CONN \
          --set-env-vars CLOUDSQL_INSTANCE=$CONN,DB_NAME=bugdash,DB_USER=postgres,DB_PASS=${{ secrets.DB_PASS }} \
          --set-env-vars GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }},REGION=${{ secrets.GCP_REGION }} \
          --set-env-vars PUBSUB_TOPIC=bugdash-tasks,GCS_BUCKET=bugdash-artifacts-${{ secrets.GCP_PROJECT_ID }} \
          --cpu 1 --memory 512Mi --max-instances 3
